### ISSUE TITLE
Error when running Main.py 

### ISSUE THREAD

**Issue by Open1333** [kombucha7/bbdc-bot#3]
Got this error when running Main.py. 

![image](https://github.com/kombucha7/bbdc-bot/assets/109139634/99a58630-daed-48e2-9280-339501b184cb)

**Comment by kombucha7** [comment]
Unfortunately, I am unable to replicate your issue on my end. Can I check if you have installed chromedriver/geckodriver/driver for your browser of choice on your device previously?

**Comment by Open1333** [comment]
I do not have chromedriver/geckodriver/driver installed.

**Comment by kombucha7** [comment]
Please pull latest and try again

**Comment by Open1333** [comment]
Not sure why i tried again is still the same error.

![image](https://github.com/kombucha7/bbdc-bot/assets/109139634/dc204dc5-8206-4b3f-afe5-f58830132e8b)

**Comment by kombucha7** [comment]
Unfortunately, I am unable to reproduce this on python versions 3.9-3.11 on both mac and windows devices that I have. Looking at the logs, there isn't any error code or exception from selenium or python for me to work with either as the backtrace only shows C exceptions.
